const admin = [
  {
    id: 1,
    username: "jdoe",
    fullName: "John Doe",
    email: "jdoe@example.com",
    role: "HR Admin",
    status: "Active",
    phone: "+1-555-123-4567",
  },
  {
    id: 2,
    username: "asmith",
    fullName: "Alice Smith",
    email: "asmith@example.com",
    role: "Finance Admin",
    status: "Inactive",
    phone: "+1-555-234-5678",
  },
  {
    id: 3,
    username: "bwayne",
    fullName: "Bruce Wayne",
    email: "bwayne@example.com",
    role: "Teachers Admin",
    status: "Active",
    phone: "+1-555-345-6789",
  },
  {
    id: 4,
    username: "ckent",
    fullName: "Clark Kent",
    email: "ckent@example.com",
    role: "Parents Admin",
    status: "Inactive",
    phone: "+1-555-456-7890",
  },
  {
    id: 5,
    username: "dprince",
    fullName: "Diana Prince",
    email: "dprince@example.com",
    role: "Students Admin",
    status: "Active",
    phone: "+1-555-567-8901",
  },
  {
    id: 6,
    username: "pparker",
    fullName: "Peter Parker",
    email: "pparker@example.com",
    role: "Messaging Admin",
    status: "Active",
    phone: "+1-555-678-9012",
  },
  {
    id: 7,
    username: "tstark",
    fullName: "Tony Stark",
    email: "tstark@example.com",
    role: "Events Admin",
    status: "Inactive",
    phone: "+1-555-789-0123",
  },
  {
    id: 8,
    username: "sscott",
    fullName: "Scott Scott",
    email: "sscott@example.com",
    role: "Notice Board Admin",
    status: "Active",
    phone: "+1-555-890-1234",
  },
  {
    id: 9,
    username: "bwilliams",
    fullName: "Barry Williams",
    email: "bwilliams@example.com",
    role: "School Calendar Admin",
    status: "Inactive",
    phone: "+1-555-901-2345",
  },
  {
    id: 10,
    username: "sjobs",
    fullName: "Steve Jobs",
    email: "sjobs@example.com",
    role: "Subjects Admin",
    status: "Active",
    phone: "+1-555-012-3456",
  },
  {
    id: 11,
    username: "bgates",
    fullName: "Bill Gates",
    email: "bgates@example.com",
    role: "CMS Admin",
    status: "Active",
    phone: "+1-555-234-1111",
  },
  {
    id: 12,
    username: "eclark",
    fullName: "Emma Clark",
    email: "eclark@example.com",
    role: "Admin Users Admin",
    status: "Inactive",
    phone: "+1-555-222-1111",
  },
  {
    id: 13,
    username: "mjackson",
    fullName: "Michael Jackson",
    email: "mjackson@example.com",
    role: "Dashboard Admin",
    status: "Active",
    phone: "+1-555-333-1111",
  },
  {
    id: 14,
    username: "tkim",
    fullName: "Thomas Kim",
    email: "tkim@example.com",
    role: "HR Admin",
    status: "Active",
    phone: "+1-555-444-1111",
  },
  {
    id: 15,
    username: "rpatel",
    fullName: "Ravi Patel",
    email: "rpatel@example.com",
    role: "Finance Admin",
    status: "Inactive",
    phone: "+1-555-555-1111",
  },
  {
    id: 16,
    username: "lkhan",
    fullName: "Lara Khan",
    email: "lkhan@example.com",
    role: "Teachers Admin",
    status: "Active",
    phone: "+1-555-666-1111",
  },
  {
    id: 17,
    username: "slee",
    fullName: "Sophia Lee",
    email: "slee@example.com",
    role: "Parents Admin",
    status: "Active",
    phone: "+1-555-777-1111",
  },
  {
    id: 18,
    username: "ahassan",
    fullName: "Ali Hassan",
    email: "ahassan@example.com",
    role: "Students Admin",
    status: "Inactive",
    phone: "+1-555-888-1111",
  },
  {
    id: 19,
    username: "jwilson",
    fullName: "Jack Wilson",
    email: "jwilson@example.com",
    role: "Messaging Admin",
    status: "Active",
    phone: "+1-555-999-1111",
  },
  {
    id: 20,
    username: "cgarcia",
    fullName: "Carlos Garcia",
    email: "cgarcia@example.com",
    role: "Events Admin",
    status: "Inactive",
    phone: "+1-555-000-1111",
  },
];

export { admin };
