
export const admin = [
  {
    id: 1,
    username: "superadmin",
    fullName: "Super Admin",
    email: "admin1@school.com",
    phone: "+2348012345678",
    role: "System Admin",
    status: "Active",
    permissions: [
      { module: "Dashboard", edit: true, view: true, delete: true },
      { module: "HR", edit: true, view: true, delete: false },
    ],
  },
  {
    id: 2,
    username: "hradmin",
    fullName: "HR Manager",
    email: "admin2@school.com",
    phone: "+2348012345679",
    role: "HR Admin",
    status: "Inactive",
    permissions: [
      { module: "HR", edit: true, view: true, delete: true },
      { module: "Teachers", edit: false, view: true, delete: false },
    ],
  },
  {
    id: 3,
    username: "teacheradmin",
    fullName: "Teacher Admin",
    email: "admin3@school.com",
    phone: "+2348012345680",
    role: "Teacher Admin",
    status: "Active",
    permissions: [
      { module: "Teachers", edit: true, view: true, delete: false },
      { module: "Students", edit: false, view: true, delete: false },
    ],
  },
  {
    id: 4,
    username: "studentadmin",
    fullName: "Student Admin",
    email: "admin4@school.com",
    phone: "+2348012345681",
    role: "Student Admin",
    status: "Inactive",
    permissions: [
      { module: "Students", edit: true, view: true, delete: true },
      { module: "Parents", edit: false, view: true, delete: false },
    ],
  },
  {
    id: 5,
    username: "financeadmin",
    fullName: "Finance Admin",
    email: "admin5@school.com",
    phone: "+2348012345682",
    role: "Finance Admin",
    status: "Active",
    permissions: [
      { module: "Finance", edit: true, view: true, delete: false },
      { module: "Events", edit: false, view: true, delete: false },
    ],
  },
  {
    id: 6,
    username: "eventadmin",
    fullName: "Events Manager",
    email: "admin6@school.com",
    phone: "+2348012345683",
    role: "Event Admin",
    status: "Inactive",
    permissions: [
      { module: "Events", edit: true, view: true, delete: true },
      { module: "Notice Board", edit: true, view: true, delete: false },
    ],
  },
  {
    id: 7,
    username: "messagingadmin",
    fullName: "Messaging Admin",
    email: "admin7@school.com",
    phone: "+2348012345684",
    role: "Messaging Admin",
    status: "Active",
    permissions: [
      { module: "Messaging", edit: true, view: true, delete: true },
      { module: "Parents", edit: false, view: true, delete: false },
    ],
  },
  {
    id: 8,
    username: "parentadmin",
    fullName: "Parent Admin",
    email: "admin8@school.com",
    phone: "+2348012345685",
    role: "Parent Admin",
    status: "Inactive",
    permissions: [
      { module: "Parents", edit: true, view: true, delete: false },
      { module: "Students", edit: true, view: true, delete: false },
    ],
  },
  {
    id: 9,
    username: "noticeadmin",
    fullName: "Notice Manager",
    email: "admin9@school.com",
    phone: "+2348012345686",
    role: "Notice Admin",
    status: "Active",
    permissions: [
      { module: "Notice Board", edit: true, view: true, delete: true },
      { module: "School Calendar", edit: false, view: true, delete: false },
    ],
  },
  {
    id: 10,
    username: "calendaradmin",
    fullName: "Calendar Admin",
    email: "admin10@school.com",
    phone: "+2348012345687",
    role: "Calendar Admin",
    status: "Inactive",
    permissions: [
      { module: "School Calendar", edit: true, view: true, delete: false },
      { module: "Subjects", edit: false, view: true, delete: false },
    ],
  },
  {
    id: 11,
    username: "subjectadmin",
    fullName: "Subject Admin",
    email: "admin11@school.com",
    phone: "+2348012345688",
    role: "Subject Admin",
    status: "Active",
    permissions: [
      { module: "Subjects", edit: true, view: true, delete: false },
      { module: "CMS", edit: false, view: true, delete: false },
    ],
  },
  {
    id: 12,
    username: "cmsadmin",
    fullName: "CMS Admin",
    email: "admin12@school.com",
    phone: "+2348012345689",
    role: "CMS Admin",
    status: "Inactive",
    permissions: [
      { module: "CMS", edit: true, view: true, delete: true },
      { module: "Dashboard", edit: false, view: true, delete: false },
    ],
  },
  {
    id: 13,
    username: "libraryadmin",
    fullName: "Library Admin",
    email: "admin13@school.com",
    phone: "+2348012345690",
    role: "Library Admin",
    status: "Active",
    permissions: [
      { module: "CMS", edit: true, view: true, delete: false },
      { module: "Finance", edit: false, view: true, delete: false },
    ],
  },
  {
    id: 14,
    username: "transportadmin",
    fullName: "Transport Admin",
    email: "admin14@school.com",
    phone: "+2348012345691",
    role: "Transport Admin",
    status: "Inactive",
    permissions: [
      { module: "Events", edit: true, view: true, delete: false },
      { module: "HR", edit: false, view: true, delete: false },
    ],
  },
  {
    id: 15,
    username: "sportsadmin",
    fullName: "Sports Admin",
    email: "admin15@school.com",
    phone: "+2348012345692",
    role: "Sports Admin",
    status: "Active",
    permissions: [
      { module: "Dashboard", edit: true, view: true, delete: false },
      { module: "Students", edit: true, view: true, delete: false },
    ],
  },
  {
    id: 16,
    username: "ictadmin",
    fullName: "ICT Admin",
    email: "admin16@school.com",
    phone: "+2348012345693",
    role: "ICT Admin",
    status: "Inactive",
    permissions: [
      { module: "CMS", edit: true, view: true, delete: true },
      { module: "Teachers", edit: true, view: true, delete: false },
    ],
  },
  {
    id: 17,
    username: "hosteladmin",
    fullName: "Hostel Admin",
    email: "admin17@school.com",
    phone: "+2348012345694",
    role: "Hostel Admin",
    status: "Active",
    permissions: [
      { module: "Finance", edit: true, view: true, delete: false },
      { module: "Parents", edit: false, view: true, delete: false },
    ],
  },
  {
    id: 18,
    username: "examadmin",
    fullName: "Exam Admin",
    email: "admin18@school.com",
    phone: "+2348012345695",
    role: "Exam Admin",
    status: "Inactive",
    permissions: [
      { module: "Subjects", edit: true, view: true, delete: false },
      { module: "Students", edit: false, view: true, delete: false },
    ],
  },
  {
    id: 19,
    username: "resultadmin",
    fullName: "Result Admin",
    email: "admin19@school.com",
    phone: "+2348012345696",
    role: "Result Admin",
    status: "Active",
    permissions: [
      { module: "Students", edit: true, view: true, delete: true },
      { module: "Teachers", edit: false, view: true, delete: false },
    ],
  },
  {
    id: 20,
    username: "admissionadmin",
    fullName: "Admission Admin",
    email: "admin20@school.com",
    phone: "+2348012345697",
    role: "Admission Admin",
    status: "Inactive",
    permissions: [
      { module: "Parents", edit: true, view: true, delete: false },
      { module: "Students", edit: true, view: true, delete: false },
    ],
  },
];
